<div class="cnkt-main">
   <div class="group postbox">
      <p><?php _e('Copy and paste the following WP_Query into a <a href="http://codex.wordpress.org/Theme_Development#Template_Files" target="_blank">PHP template</a> within your WordPress theme.', 'easy-query'); ?></p>
      
      <textarea id="query-output"></textarea>
      
      <div class="row no-brd">
			<p class="back2top"><a href="#wpcontent"><i class="fa fa-angle-up"></i>&nbsp; <?php _e('Back to Top', 'easy-query'); ?></a></p>					
	   </div>
   </div>
</div>

<div class="cnkt-sidebar">
      
      <div class="cta postbox">
         <h3><?php _e('Save Your Query', 'easy-query'); ?></h3>
         <div class="cta-wrap save-query-wrap">
   	      <label for="ewpq_query_alias-alias"><?php _e('Query Alias', 'easy-query'); ?></label>
   	      <input type="text" id="ewpq_query_alias" class="ewpq_query_alias" value="" autocomplete="off" placeholder="<?php _e('Enter a query alias', 'easy-query'); ?>">
            <div class="saving"></div>
            <div class="saved-response-text"></div>
         </div>
         <div id="major-publishing-actions" class="ewpq-save-settings">
   		   <button type="button" class="button button-primary" id="ewpq-save-query"><?php _e('Save Query', 'easy-query'); ?></button>	
            <div class="clear"></div>
         </div>         
      </div>
      
      <div class="cta postbox">
         <h3><?php _e('About Your Query', 'easy-query'); ?></h3>
         <div class="cta-wrap">
            <p><?php _e('This WP_Query has been generated by the selected parameters from the Query Builder tab. To make adjustments to this query you should return to the Query Builder and make your edits.', 'easy-query'); ?></p>
         </div>
      </div>
      
</div>